### ISSUE TITLE
启动weread_2_notion.py报错No module named 'notion.notion'

### ISSUE THREAD

**Issue by Zison-Yung** [DuckDuck88/weread2notion#1]
一开始在pip install requirements.txt时，提示 【Could not find a version that satisfies the requirement notion-client==1.0.0 (from -r requirements.txt (line 2)) (from versions: )】，我在网上也没找到notion-client的包，于是把requirements里的【notion-client==1.0.0】改成了【notion】，最后在python weread_2_notion.py时报错【 File "weread_2_notion.py", line 6, in <module>
    from notion.notion import NotionClient
ModuleNotFoundError: No module named 'notion.notion'】

**Comment by DuckDuck88** [comment]
你好，这个包在官方源里有的。[包地址](https://pypi.org/project/notion-client)。
解决办法：
1. 检查 pip 配置是否换了pip其他源，具体方法可以百度
2. 手动下载包安装
